from __future__ import annotations

import argparse
import asyncio
import json
import sys
from datetime import UTC, datetime
from uuid import uuid4

from rich.console import Console
from vehicle_search_agent.runner import VehicleSearchSession

DEFAULT_TURNS = (
    "Show me the top three used commercial vehicles under 20 lakh.",
    "What is the payload of the first one?",
)

sys.stdout.reconfigure(encoding="utf-8")
console = Console()


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a live text smoke test against the Vivi vehicle-search agent.")
    parser.add_argument(
        "--turn",
        action="append",
        dest="turns",
        help="User turn to send. Repeat this option for a multi-turn conversation.",
    )
    parser.add_argument(
        "--session-id", help="Optional persistent session ID. A unique smoke-test ID is generated by default."
    )
    return parser.parse_args()


async def _run(turns: list[str], session_id: str) -> None:
    session = VehicleSearchSession(session_id)

    console.print("SESSION>", session_id, style="bold magenta", markup=False)

    for index, transcript in enumerate(turns, start=1):
        console.rule(f"Turn {index}", style="dim")
        console.print("USER>", transcript, style="bold cyan", markup=False)

        result = await session.run_text_turn(transcript)
        timings = {name: value for name, value in result.metrics.model_dump().items() if value is not None}

        console.print("VIVI>", result.spoken_response, style="green", markup=False)
        console.print("STATE>", result.active_filters.model_dump_json(exclude_none=True), style="dim", markup=False)
        console.print("RESULT_IDS>", json.dumps(result.last_result_ids), style="dim", markup=False)
        console.print("MODEL>", result.model_used, style="dim", markup=False)
        console.print("TIMINGS_MS>", json.dumps(timings, sort_keys=True), style="dim", markup=False)
        console.print(
            "USAGE>",
            result.usage.model_dump_json(exclude_none=True),
            style="dim",
            markup=False,
        )


def main() -> None:
    arguments = _arguments()
    turns = arguments.turns or list(DEFAULT_TURNS)
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    session_id = arguments.session_id or f"cli-smoke-{timestamp}-{uuid4().hex[:8]}"

    asyncio.run(_run(turns, session_id))


if __name__ == "__main__":
    main()
