[theme]
base = "dark"
primaryColor = "#F59E0B"
backgroundColor = "#101318"
secondaryBackgroundColor = "#181D25"
textColor = "#F4F6F8"
font = "sans-serif"

[server]
headless = true
folderWatchList = ["app"]
